In [38]:
import numpy as np
from quantfreedom.helper_funcs import cart_product
from typing import NamedTuple


In [39]:
class IndicatorSettingsArrays(NamedTuple):
    signal_above_slow: np.array
    ema_fast_length: np.array
    ema_mid_length: np.array
    ema_slow_length: np.array


cart_arrays = cart_product(
    named_tuple=IndicatorSettingsArrays(
        signal_above_slow=np.array([True, False]),
        ema_fast_length=np.arange(5, 31, 5),
        ema_mid_length=np.arange(10, 51, 10),
        ema_slow_length=np.arange(30, 121, 30),
    )
)

indicator_settings_arrays: IndicatorSettingsArrays = IndicatorSettingsArrays(
    signal_above_slow=cart_arrays[0].astype(np.bool_),
    ema_fast_length=cart_arrays[1].astype(np.int_),
    ema_mid_length=cart_arrays[2].astype(np.int_),
    ema_slow_length=cart_arrays[3].astype(np.int_),
)

In [40]:
cart_arrays.T

array([[  1.,   5.,  10.,  30.],
       [  1.,   5.,  10.,  60.],
       [  1.,   5.,  10.,  90.],
       [  1.,   5.,  10., 120.],
       [  1.,   5.,  20.,  30.],
       [  1.,   5.,  20.,  60.],
       [  1.,   5.,  20.,  90.],
       [  1.,   5.,  20., 120.],
       [  1.,   5.,  30.,  30.],
       [  1.,   5.,  30.,  60.],
       [  1.,   5.,  30.,  90.],
       [  1.,   5.,  30., 120.],
       [  1.,   5.,  40.,  30.],
       [  1.,   5.,  40.,  60.],
       [  1.,   5.,  40.,  90.],
       [  1.,   5.,  40., 120.],
       [  1.,   5.,  50.,  30.],
       [  1.,   5.,  50.,  60.],
       [  1.,   5.,  50.,  90.],
       [  1.,   5.,  50., 120.],
       [  1.,  10.,  10.,  30.],
       [  1.,  10.,  10.,  60.],
       [  1.,  10.,  10.,  90.],
       [  1.,  10.,  10., 120.],
       [  1.,  10.,  20.,  30.],
       [  1.,  10.,  20.,  60.],
       [  1.,  10.,  20.,  90.],
       [  1.,  10.,  20., 120.],
       [  1.,  10.,  30.,  30.],
       [  1.,  10.,  30.,  60.],
       [  

In [41]:
(cart_arrays[1] < cart_arrays[2]) & (cart_arrays[2] < cart_arrays[3])

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [44]:
cart_arrays.T[(cart_arrays[1] < cart_arrays[2]) & (cart_arrays[2] < cart_arrays[3])]

array([[  1.,   5.,  10.,  30.],
       [  1.,   5.,  10.,  60.],
       [  1.,   5.,  10.,  90.],
       [  1.,   5.,  10., 120.],
       [  1.,   5.,  20.,  30.],
       [  1.,   5.,  20.,  60.],
       [  1.,   5.,  20.,  90.],
       [  1.,   5.,  20., 120.],
       [  1.,   5.,  30.,  60.],
       [  1.,   5.,  30.,  90.],
       [  1.,   5.,  30., 120.],
       [  1.,   5.,  40.,  60.],
       [  1.,   5.,  40.,  90.],
       [  1.,   5.,  40., 120.],
       [  1.,   5.,  50.,  60.],
       [  1.,   5.,  50.,  90.],
       [  1.,   5.,  50., 120.],
       [  1.,  10.,  20.,  30.],
       [  1.,  10.,  20.,  60.],
       [  1.,  10.,  20.,  90.],
       [  1.,  10.,  20., 120.],
       [  1.,  10.,  30.,  60.],
       [  1.,  10.,  30.,  90.],
       [  1.,  10.,  30., 120.],
       [  1.,  10.,  40.,  60.],
       [  1.,  10.,  40.,  90.],
       [  1.,  10.,  40., 120.],
       [  1.,  10.,  50.,  60.],
       [  1.,  10.,  50.,  90.],
       [  1.,  10.,  50., 120.],
       [  