In [1]:
import numpy as np
from datetime import datetime
from quantfreedom import dl_ex_candles
from plotly.subplots import make_subplots
from plotly.graph_objects import Scatter, Candlestick
from quantfreedom.indicators.tv_indicators import rsi_tv

%load_ext autoreload
%autoreload 2

In [2]:
lb_1 = 2

arr_1 = np.random.randint(10, 30, 10)
print(arr_1)
p_arr_1 = np.full(arr_1.shape, np.nan)

p_arr_1[lb_1:] = arr_1[:-lb_1]

p_arr_1

[12 28 26 14 19 24 12 24 13 29]


array([nan, nan, 12., 28., 26., 14., 19., 24., 12., 24.])

In [29]:
lb_2 = 2

arr_2 = np.random.randint(10, 30, 10)
print(arr_2)
p_arr_2 = np.full((arr_2.size, lb_2), np.nan)
g_arr_2 = arr_2[lb_2:].size

p_arr_2[lb_2:, 0] = arr_2[:g_arr_2]
p_arr_2[lb_2:, 1] = arr_2[1 : g_arr_2 + 1]
p_arr_2

[12 16 24 26 26 15 20 20 11 29]


array([[nan, nan],
       [nan, nan],
       [12., 16.],
       [16., 24.],
       [24., 26.],
       [26., 26.],
       [26., 15.],
       [15., 20.],
       [20., 20.],
       [20., 11.]])

In [4]:
arr_2_2d = arr_2.reshape(arr_2.size, -1)
print(arr_2_2d)
arr_2_2d - p_arr_2

[[11]
 [19]
 [17]
 [15]
 [27]
 [25]
 [17]
 [27]
 [19]
 [28]]


array([[ nan,  nan],
       [ nan,  nan],
       [  6.,  -2.],
       [ -4.,  -2.],
       [ 10.,  12.],
       [ 10.,  -2.],
       [-10.,  -8.],
       [  2.,  10.],
       [  2.,  -8.],
       [  1.,   9.]])

In [5]:
lb_3 = 7

arr_3 = np.random.randint(10, 30, 10)
print(arr_3)
p_arr_3 = np.full((arr_3.size, lb_3), np.nan)
g_arr_3 = arr_3[lb_3:].size


for col in range(lb_3):
    p_arr_3[lb_3:, col] = arr_3[col : g_arr_3 + col]

p_arr_3

[14 10 15 29 22 25 15 24 19 24]


array([[nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [14., 10., 15., 29., 22., 25., 15.],
       [10., 15., 29., 22., 25., 15., 24.],
       [15., 29., 22., 25., 15., 24., 19.]])

In [30]:
lb_4 = 3
include = True
num_cols = lb_4

if include:
    num_cols += 1

arr_4 = np.random.randint(10, 30, 10).astype(np.float_)
arr_4[:2] = np.nan
print(arr_4)

arr_4_size = arr_4.size

a_arr_4 = np.where(np.isnan(arr_4))[0].size

p_arr_4 = np.full((arr_4_size, num_cols), np.nan)
g_arr_4 = arr_4[lb_4:].size

s_pa = lb_4 + a_arr_4

for col in range(num_cols):
    p_arr_4[s_pa:, col] = arr_4[col + a_arr_4 : g_arr_4 + col]

p_arr_4

[nan nan 13. 29. 15. 27. 18. 25. 17. 16.]


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [13., 29., 15., 27.],
       [29., 15., 27., 18.],
       [15., 27., 18., 25.],
       [27., 18., 25., 17.],
       [18., 25., 17., 16.]])

In [31]:
lb_5 = 3
lb_6 = 6
lb_7 = 10

arr_5 = np.random.randint(10, 30, 10).astype(np.float_)
arr_5[:2] = np.nan
arr_6 = np.random.randint(10, 30, 15)
arr_7 = np.random.randint(10, 30, 25).astype(np.float_)
arr_7[:5] = np.nan

arr_5_size = arr_5.size
a_arr_5 = np.where(np.isnan(arr_5))[0].size
p_arr_5 = np.full((arr_5_size, lb_5 + 1), np.nan)
g_arr_5 = arr_5[lb_5:].size
s_pa_5 = lb_5 + a_arr_5

arr_6_size = arr_6.size
a_arr_6 = np.where(np.isnan(arr_6))[0].size
p_arr_6 = np.full((arr_6_size, lb_6), np.nan)
g_arr_6 = arr_6[lb_6:].size
s_pa_6 = lb_6 + a_arr_6

arr_7_size = arr_7.size
a_arr_7 = np.where(np.isnan(arr_7))[0].size
p_arr_7 = np.full((arr_7_size, lb_7), np.nan)
g_arr_7 = arr_7[lb_7:].size
s_pa_7 = lb_7 + a_arr_7

col = 0

while col < lb_5 + 1:
    p_arr_5[s_pa_5:, col] = arr_5[col + a_arr_5 : g_arr_5 + col]
    p_arr_6[s_pa_6:, col] = arr_6[col + a_arr_6 : g_arr_6 + col]
    p_arr_7[s_pa_7:, col] = arr_7[col + a_arr_7 : g_arr_7 + col]
    col += 1

while col < lb_6:
    p_arr_6[s_pa_6:, col] = arr_6[col + a_arr_6 : g_arr_6 + col]
    p_arr_7[s_pa_7:, col] = arr_7[col + a_arr_7 : g_arr_7 + col]
    col += 1
    
while col < lb_7:
    p_arr_7[s_pa_7:, col] = arr_7[col + a_arr_7 : g_arr_7 + col]
    col += 1

print(arr_5)
print(p_arr_5)
print(arr_6)
print(p_arr_6)
print(arr_7)
print(p_arr_7)

[nan nan 20. 24. 20. 27. 13. 29. 17. 24.]
[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [20. 24. 20. 27.]
 [24. 20. 27. 13.]
 [20. 27. 13. 29.]
 [27. 13. 29. 17.]
 [13. 29. 17. 24.]]
[14 15 29 24 18 23 26 18 17 22 18 16 27 18 20]
[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [14. 15. 29. 24. 18. 23.]
 [15. 29. 24. 18. 23. 26.]
 [29. 24. 18. 23. 26. 18.]
 [24. 18. 23. 26. 18. 17.]
 [18. 23. 26. 18. 17. 22.]
 [23. 26. 18. 17. 22. 18.]
 [26. 18. 17. 22. 18. 16.]
 [18. 17. 22. 18. 16. 27.]
 [17. 22. 18. 16. 27. 18.]]
[nan nan nan nan nan 22. 11. 22. 10. 10. 20. 22. 22. 28. 14. 18. 19. 18.
 27. 14. 16. 20. 17. 24. 20.]
[[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan n

In [8]:
def np_lb_one(
    arr: np.ndarray,
    include: bool,
    lb: int,
) -> np.ndarray:
    num_cols = lb

    if include:
        num_cols += 1

    arr_size = arr.size
    p_arr = np.full((arr_size, num_cols), np.nan)  # previous array
    g_arr = arr_size - lb  # grab end of arr index
    a_arr = np.where(np.isnan(arr))[0].size  # add total number of nans to p arr start and arr start in loop

    s_pa = lb + a_arr  # start for previous array

    for col in range(num_cols):
        p_arr[s_pa:, col] = arr[col + a_arr : g_arr + col]

    return p_arr

In [32]:
test_arr = np.random.randint(10, 30, 10).astype(np.float_)
test_arr[:2] = np.nan
print(test_arr)
np_lb_one(
    arr=test_arr,
    include=True,
    lb=3,
)

[nan nan 10. 18. 26. 24. 27. 14. 17. 17.]


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [10., 18., 26., 24.],
       [18., 26., 24., 27.],
       [26., 24., 27., 14.],
       [24., 27., 14., 17.],
       [27., 14., 17., 17.]])

In [10]:
candles = dl_ex_candles(
    exchange="mufex",
    symbol="BTCUSDT",
    timeframe="5m",
    since_datetime=datetime(2024, 1, 1),
)

In [11]:
rsi = rsi_tv(
    source=candles.candle_close_prices,
    length=14,
).round(2)

In [12]:
rsi_lb = np_lb_one(
    arr=rsi,
    include=True,
    lb=4,
)
rsi_lb[12:25]

array([[  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [56.06, 59.22, 56.72, 57.87, 64.11],
       [59.22, 56.72, 57.87, 64.11, 73.53],
       [56.72, 57.87, 64.11, 73.53, 70.33],
       [57.87, 64.11, 73.53, 70.33, 70.13],
       [64.11, 73.53, 70.33, 70.13, 66.12],
       [73.53, 70.33, 70.13, 66.12, 59.77],
       [70.33, 70.13, 66.12, 59.77, 54.86]])

In [13]:
rsi[12:25]

array([  nan,   nan, 56.06, 59.22, 56.72, 57.87, 64.11, 73.53, 70.33,
       70.13, 66.12, 59.77, 54.86])

In [14]:
rsi_lb_result = rsi_lb < 30
rsi_lb_result

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       ...,
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [15]:
rsi_lb_result_any_0 = rsi_lb_result.any(axis=0)
rsi_lb_result_any_0

array([ True,  True,  True,  True,  True])

In [16]:
rsi_lb_result_any_1 = rsi_lb_result.any(axis=1)
rsi_lb_result_any_1

array([False, False, False, ..., False, False, False])

In [17]:
np.where(rsi_lb_result_any_1)

(array([  44,   45,   46,   47,   48,  428,  429,  430,  431,  432,  471,
         472,  473,  474,  475,  670,  671,  672,  673,  674,  710,  711,
         712,  713,  714,  715,  716,  717,  718,  719,  720,  721,  722,
         723,  724,  725,  726,  727, 1173, 1174, 1175, 1176, 1177, 1178,
        1179, 1283, 1284, 1285, 1286, 1287], dtype=int64),)

In [18]:
rsi_lb_result_any_1[428]

True

In [19]:
rsi_lb_result[428]

array([False, False, False, False,  True])

In [20]:
rsi_lb_result_all_1 = rsi_lb_result.all(axis=1)
rsi_lb_result_all_1

array([False, False, False, ..., False, False, False])

In [21]:
print(rsi_lb_result[723])
print(rsi_lb_result_any_1[723])
print(rsi_lb_result_all_1[723])

[ True  True  True  True  True]
True
True


In [22]:
candles = dl_ex_candles(
    exchange="mufex",
    symbol="BTCUSDT",
    timeframe="5m",
    since_datetime=datetime(2024, 5, 16),
    candles_to_dl=500
)
rsi = rsi_tv(
    source=candles.candle_close_prices,
    length=14,
).round(2)
rsi_lb = np_lb_one(
    arr=rsi,
    include=True,
    lb=4,
)
result = (rsi_lb < 30).all(axis=1)
signal_indexes = np.where(result)[0]
signal_indexes

array([212, 213], dtype=int64)

In [23]:
fig = make_subplots(
    cols=1,
    rows=2,
    shared_xaxes=True,
    subplot_titles=["Candles", "RSI"],
    row_heights=[0.6, 0.4],
    vertical_spacing=0.1,
)

datetimes = candles.candle_open_datetimes
# Candlestick chart for pricing
fig.append_trace(
    Candlestick(
        x=datetimes,
        open=candles.candle_open_prices,
        high=candles.candle_high_prices,
        low=candles.candle_low_prices,
        close=candles.candle_close_prices,
        name="Candles",
    ),
    col=1,
    row=1,
)
fig.append_trace(
    Scatter(
        x=datetimes[signal_indexes],
        y=candles.candle_close_prices[signal_indexes],
        mode="markers",
        name="entries",
        marker=dict(
            size=12,
            symbol="circle",
            color="#00F6FF",
            line=dict(
                width=1,
                color="DarkSlateGrey",
            ),
        ),
    ),
    row=1,
    col=1,
)
fig.append_trace(
    Scatter(
        x=datetimes,
        y=rsi,
        name="RSI",
        line_color="yellow",
    ),
    row=2,
    col=1,
)
fig.append_trace(
    Scatter(
        x=datetimes[[0, -1]],
        y=[30, 30],
        name="Below",
        line_color="#FF6D00",
    ),
    row=2,
    col=1,
)
fig.append_trace(
    Scatter(
        x=datetimes[signal_indexes],
        y=rsi[signal_indexes],
        mode="markers",
        name="entries",
        marker=dict(
            size=12,
            symbol="circle",
            color="#00F6FF",
            line=dict(
                width=1,
                color="DarkSlateGrey",
            ),
        ),
    ),
    row=2,
    col=1,
)
# Update options and show plot
fig.update_layout(height=800, xaxis_rangeslider_visible=False)
fig.show()