In [50]:
import numpy as np
from quantfreedom import dl_ex_candles
from datetime import datetime
from quantfreedom.indicators.tv_indicators import rsi_tv

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
lb_1 = 2

arr_1 = np.arange(10)
p_arr_1 = np.full(arr_1.shape, np.nan)

p_arr_1[lb_1:] = arr_1[:-lb_1]

p_arr_1

array([nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [52]:
lb_2 = 3

arr_2 = np.arange(10)
p_arr_2 = np.full((arr_2.size, lb_2), np.nan)
g_arr_2 = arr_2[lb_2:].size

p_arr_2[lb_2:, 0] = arr_2[:g_arr_2]
p_arr_2[lb_2:, 1] = arr_2[1 : g_arr_2 + 1]
p_arr_2[lb_2:, 2] = arr_2[2 : g_arr_2 + 2]
p_arr_2

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [ 0.,  1.,  2.],
       [ 1.,  2.,  3.],
       [ 2.,  3.,  4.],
       [ 3.,  4.,  5.],
       [ 4.,  5.,  6.],
       [ 5.,  6.,  7.],
       [ 6.,  7.,  8.]])

In [53]:
lb_3 = 7
include = False
num_cols = lb_3

arr_3 = np.arange(20)
p_arr_3 = np.full((arr_3.size, lb_3), np.nan)
g_arr_3 = arr_3[lb_3:].size


for col in range(lb_3):
    p_arr_3[lb_3:, col] = arr_3[col : g_arr_3 + col]

p_arr_3

array([[nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 6.,  7.,  8.,  9., 10., 11., 12.],
       [ 7.,  8.,  9., 10., 11., 12., 13.],
       [ 8.,  9., 10., 11., 12., 13., 14.],
       [ 9., 10., 11., 12., 13., 14., 15.],
       [10., 11., 12., 13., 14., 15., 16.],
       [11., 12., 13., 14., 15., 16., 17.],
       [12., 13., 14., 15., 16., 17., 18.]])

In [54]:
lb_4 = 3
include = False
num_cols = lb_4

if include:
    num_cols += 1

arr_4 = np.array([np.nan, np.nan, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0])

arr_4_size = arr_4.size

a_arr_4 = np.where(np.isnan(arr_4))[0].size

p_arr_4 = np.full((arr_4_size, num_cols), np.nan)
g_arr_4 = arr_4[lb_4:].size

s_pa = lb_4 + a_arr_4

for col in range(num_cols):
    p_arr_4[s_pa:, col] = arr_4[col + a_arr_4 : g_arr_4 + col]

p_arr_4

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [ 0.,  1.,  2.],
       [ 1.,  2.,  3.],
       [ 2.,  3.,  4.],
       [ 3.,  4.,  5.],
       [ 4.,  5.,  6.]])

In [55]:
def np_lb_one(
    arr: np.ndarray,
    include: bool,
    lb: int,
) -> np.ndarray:
    num_cols = lb

    if include:
        num_cols += 1

    arr_size = arr.size
    p_arr = np.full((arr_size, num_cols), np.nan)  # previous array
    g_arr = arr_size - lb  # grab end of arr index
    a_arr = np.where(np.isnan(arr))[0].size  # add total number of nans to p arr start and arr start in loop

    s_pa = lb + a_arr  # start for previous array

    for col in range(num_cols):
        p_arr[s_pa:, col] = arr[col + a_arr : g_arr + col]

    return p_arr

In [56]:
np_lb_one(
    arr=np.array([np.nan, np.nan, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]),
    include=False,
    lb=3,
)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [ 0.,  1.,  2.],
       [ 1.,  2.,  3.],
       [ 2.,  3.,  4.],
       [ 3.,  4.,  5.],
       [ 4.,  5.,  6.]])

In [57]:
candles = dl_ex_candles(
    exchange="mufex",
    symbol="BTCUSDT",
    timeframe="5m",
    since_datetime=datetime(2024, 1, 1),
)

In [58]:
rsi = rsi_tv(
    source=candles.candle_close_prices,
    length=14,
).round(2)

In [59]:
rsi_lb = np_lb_one(
    arr=rsi,
    include=False,
    lb=4,
)
rsi_lb[12:25]

array([[  nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan],
       [56.06, 59.22, 56.72, 57.87],
       [59.22, 56.72, 57.87, 64.11],
       [56.72, 57.87, 64.11, 73.53],
       [57.87, 64.11, 73.53, 70.33],
       [64.11, 73.53, 70.33, 70.13],
       [73.53, 70.33, 70.13, 66.12],
       [70.33, 70.13, 66.12, 59.77]])

In [60]:
rsi[12:25]

array([  nan,   nan, 56.06, 59.22, 56.72, 57.87, 64.11, 73.53, 70.33,
       70.13, 66.12, 59.77, 54.86])

In [61]:
rsi_lb_result = rsi_lb < 30
rsi_lb_result

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [62]:
rsi_lb_result_any_0 = rsi_lb_result.any(axis=0)
rsi_lb_result_any_0

array([ True,  True,  True,  True])

In [63]:
rsi_lb_result_any_1 = rsi_lb_result.any(axis=1)
rsi_lb_result_any_1

array([False, False, False, ..., False, False, False])

In [64]:
np.where(rsi_lb_result_any_1)

(array([  45,   46,   47,   48,  429,  430,  431,  432,  472,  473,  474,
         475,  671,  672,  673,  674,  711,  712,  713,  714,  715,  716,
         717,  718,  719,  720,  721,  722,  723,  724,  725,  726,  727,
        1174, 1175, 1176, 1177, 1178, 1179, 1284, 1285, 1286, 1287],
       dtype=int64),)

In [65]:
rsi_lb_result_any_1[45]

True

In [66]:
rsi_lb_result[45]

array([False, False, False,  True])

In [67]:
rsi_lb_result_all_1 = rsi_lb_result.all(axis=1)
rsi_lb_result_all_1

array([False, False, False, ..., False, False, False])

In [68]:
np.where(rsi_lb_result_all_1)

(array([716, 721, 722, 723, 724], dtype=int64),)

In [69]:
print(rsi_lb_result[723])
print(rsi_lb_result_any_1[723])
print(rsi_lb_result_all_1[723])

[ True  True  True  True]
True
True
