Numpy

learn more - https://numpy.org/doc/stable/user/basics.html

In [27]:
import numpy as np

In [28]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [29]:
np.zeros(2)

array([0., 0.])

In [30]:
np.ones(2)

array([1., 1.])

In [34]:
np.empty(2)

array([1.15210292e-311, 1.15222956e-311])

In [36]:
np.arange(4)

array([0, 1, 2, 3])

In [39]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [40]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)

In [44]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [45]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
array_example = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
    ],
)
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [48]:
array_example.ndim

3

In [49]:
array_example.size

24

In [50]:
array_example.shape

(3, 2, 4)

In [51]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [54]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
np.reshape(a, newshape=(1, 6))

array([[0, 1, 2, 3, 4, 5]])

In [56]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [58]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [59]:
np.expand_dims(a, axis=0)

array([[1, 2, 3, 4, 5, 6]])

In [60]:
col_vector = a[:, np.newaxis]
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [61]:
np.expand_dims(a, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [62]:
col_vector * 3

array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])

In [63]:
col_vector + col_vector

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])