Numpy indexing slicing

learn more - https://numpy.org/doc/stable/user/basics.html


In [3]:
import numpy as np

In [4]:
data = np.array([1, 2, 3])

data[1]

2

In [5]:
data[:2]

array([1, 2])

In [6]:
data[1:]

array([2, 3])

In [7]:
data[-2:]

array([2, 3])

In [8]:
data[-1]

3

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a[2, 2]

11

In [12]:
a[:2, -1]

array([4, 8])

In [13]:
a[:2, :2]

array([[1, 2],
       [5, 6]])

In [15]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
a[a < 5]

array([1, 2, 3, 4])

In [18]:
a >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [23]:
(a > 5) | (a == 5)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
np.nonzero(a < 5)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [26]:
a[np.nonzero(a < 5)]

array([1, 2, 3, 4])