In [27]:
import numpy as np
import pandas as pd
from quantfreedom.enums import CandleBodyType
from quantfreedom.helper_funcs import dl_ex_candles
from quantfreedom.indicators.tv_indicators import *
from quantfreedom.plotting.plotting_base import *
from live_strat import EngulfingEMA


np.set_printoptions(formatter={"float_kind": "{:0.2f}".format})

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [28]:
candles = dl_ex_candles(
    exchange="mufex",
    symbol="BTCUSDT",
    timeframe="5m",
    candles_to_dl=3000,
)
timestamps = candles[:, CandleBodyType.Timestamp]
datetimes = timestamps.astype("datetime64[ms]")
open_prices = candles[:, CandleBodyType.Open]
high_prices = candles[:, CandleBodyType.High]
low_prices = candles[:, CandleBodyType.Low]
close_prices = candles[:, CandleBodyType.Close]
volume = candles[:, CandleBodyType.Volume]

In [49]:
strat = EngulfingEMA(
    long_short="long",
    above_bool=np.array([True, False]),
    ema_length=np.array([200, 300]),
    falling_length=np.array([2, 3]),
)

In [57]:
strat.indicator_settings_arrays.falling_length

array([2, 3, 2, 3, 2, 3, 2, 3])

In [50]:
strat.indicator_settings_arrays.above_bool

array([ True,  True,  True,  True, False, False, False, False])

In [51]:
strat.indicator_settings_arrays.ema_length

array([200, 200, 300, 300, 200, 200, 300, 300])

In [54]:
strat.set_entries_exits_array(candles=candles, ind_set_index=5)

In [55]:
strat.plot_signals(candles=candles)