In [10]:
import numpy as np
from quantfreedom.enums import CandleBodyType
from quantfreedom.helper_funcs import dl_ex_candles
from quantfreedom.indicators.tv_indicators import *
from quantfreedom.plotting.plotting_base import *

np.set_printoptions(formatter={"float_kind": "{:0.2f}".format})

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
candles = dl_ex_candles(
    exchange="binance_us",
    symbol="BTCUSDT",
    timeframe="30m",
    candles_to_dl=300,
)

In [12]:
timestamp = candles[:, CandleBodyType.Timestamp]
close = candles[:, CandleBodyType.Close]

In [14]:
sma = sma_tv(source=close,length=20)
sma

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, 43402.43, 43404.33, 43409.61,
       43410.46, 43419.91, 43427.38, 43414.31, 43412.86, 43412.24,
       43411.34, 43402.75, 43378.88, 43364.68, 43354.42, 43344.72,
       43335.19, 43333.33, 43336.05, 43343.43, 43357.52, 43363.34,
       43373.04, 43379.37, 43368.77, 43359.13, 43355.76, 43358.91,
       43357.81, 43350.70, 43341.63, 43340.75, 43346.65, 43359.08,
       43369.78, 43382.52, 43398.35, 43408.27, 43415.64, 43439.20,
       43465.33, 43483.81, 43504.32, 43527.51, 43555.14, 43583.40,
       43615.60, 43646.59, 43676.76, 43715.84, 43756.50, 43806.89,
       43860.88, 43905.46, 43943.28, 43968.89, 43992.23, 44022.17,
       44052.20, 44065.27, 44071.96, 44088.03, 44102.53, 44118.15,
       44144.11, 44164.40, 44182.14, 44201.51, 44225.94, 44244.60,
       44260.62, 44253.00, 44234.03, 44217.61, 44202.85, 44182.31,
       44166.94, 44150.20, 44129.35, 44111.83, 44096.72, 

In [15]:
plot_sma(candles=candles,indicator=sma)

In [17]:
rsi = rsi_tv(
    source=close,
    length=14,
)
rsi

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, 61.55, 54.79, 55.58, 51.12, 46.43, 50.94, 49.64, 49.20, 53.16,
       53.30, 50.77, 45.31, 49.52, 50.40, 53.39, 52.85, 53.17, 53.70,
       56.86, 58.61, 54.57, 52.44, 57.58, 55.29, 53.95, 53.01, 54.75,
       50.08, 40.27, 41.62, 44.87, 43.50, 45.32, 40.87, 43.72, 51.92,
       58.21, 63.36, 64.78, 67.46, 66.52, 57.26, 59.90, 68.31, 68.97,
       60.27, 62.53, 61.16, 55.19, 56.49, 61.09, 58.44, 58.93, 61.84,
       64.36, 72.96, 76.75, 74.44, 69.79, 62.51, 59.94, 58.73, 60.91,
       58.22, 53.78, 54.44, 56.09, 55.84, 58.98, 54.92, 58.31, 57.15,
       61.59, 59.71, 60.68, 53.40, 52.81, 53.14, 49.81, 37.79, 40.23,
       38.15, 37.77, 38.30, 36.10, 38.83, 37.55, 44.24, 44.94, 52.41,
       53.70, 48.08, 46.91, 53.13, 50.24, 50.62, 47.07, 44.45, 45.83,
       48.79, 47.65, 46.19, 43.02, 51.58, 48.64, 51.02, 53.89, 47.60,
       40.39, 35.49, 39.96, 42.07, 46.91, 44.43, 40.74, 41.46, 44.65,
       48.51,

In [18]:
plot_rsi(
    candles=candles,
    indicator=rsi,
)

In [19]:
ema = ema_tv(source=close, length=50)
ema

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 43337.07,
       43342.72, 43353.79, 43366.14, 43381.38, 43395.44, 43402.68,
       43412.38, 43432.70, 43453.26, 43466.35, 43481.88, 43495.72,
       43504.05, 43513.46, 43527.85, 43539.54, 43551.32, 43565.90,
       43582.92, 43612.80, 43649.99, 43683.97, 43713.03, 43734.76,
       43753.27, 43769.95, 43788.80, 43804.62, 43815.84, 43827.32,
       43840.06, 43852.10, 43866.82, 43877.92, 43891.93, 43904.54,
       43921.17, 43935.87, 43950.95, 43960.42, 43969.10, 43977.68,
       43983.66, 43978.66, 43975.55, 43970.38, 43965.02, 43960.19,
       43953.45, 43948.49, 43942.59, 43940.72, 43939.33, 43942.83,
       43947.12, 43947.55, 43947.15, 43950.90, 43952.62, 43954.51,
       43954.06, 43951.85, 43950.47, 43950.79, 

In [20]:
plot_ema(candles=candles, indicator=ema)

In [21]:
sm_hist, sqz_on, no_sqz = squeeze_momentum_lazybear_tv(
    candles=candles,
    length_bb=14,
    length_kc=14,
    multi_bb=2,
    multi_kc=2,
)

In [22]:
plot_squeeze_mom_lazybear(
    candles=candles,
    indicator=sm_hist,
)